### ISSUE TITLE
Black screen when enabled/applied

### ISSUE THREAD

**Issue by rosskevin** [openvrmc/OpenVR-MotionCompensation#18]
Tried with both the 0.3.1 and the 0.3.2 hotfix, valve index and controllers.

[driver_motioncompensation.log](https://github.com/openvrmc/OpenVR-MotionCompensation/files/5152725/driver_motioncompensation.log)

## To reproduce
- start openvr
- go to ovrmc settings (one controller on)
- turn on second controller
- choose second controller
- click enable checkbox
- click apply

## Result
The result is always a black screen.  While openvr is still running, and you can see light, there is no output and I cannot navigate anywhere.  

Restarting openvr shows that ovrmc is not enabled and works fine without it.

The log is attached, nothing seems abnormal.

**Comment by rosskevin** [comment]
FYI I also tried turning on both controllers before starting ovrmc dialog, no difference.

**Comment by rosskevin** [comment]
Here is the vrserver.txt log as well as the driver log from the relevant session.

[driver_motioncompensation.log](https://github.com/openvrmc/OpenVR-MotionCompensation/files/5158210/driver_motioncompensation.log)

[vrserver.previous.txt](https://github.com/openvrmc/OpenVR-MotionCompensation/files/5158204/vrserver.previous.txt)

**Comment by Dschadu** [comment]
There is nothing obvious to see in the log files.
If you are on SteamVR beta, go back to the normal release. SteamVR beta is known to cause issues.
Otherwise I can only give you the usual trouble shooting tips: Check that your graphics-driver is up to date. Validate SteamVR installation. Try another USB port and/or disable the HMD camera.
Valve Index is known to be working from different users. The issue seems to be system-specific.

**Comment by rosskevin** [comment]
I'm going to close this for the moment because I don't want it lingering.  I won't have time to take the further steps for about two weeks, but I will follow up and post a resolution when I find it.  Thanks @Dschadu
